
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mauricio Aguilera
 */
public class plataforma extends javax.swing.JFrame {
    AdminClientes ac = new AdminClientes("./Clientes.cl");
    AdminPlatillo ap = new AdminPlatillo("./Platillos.pl");
    /**
     * Creates new form plataforma
     */
    public plataforma() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_nuevocliente = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        tf_nombrecliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sp_edadcliente = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        rb_mcliente = new javax.swing.JRadioButton();
        rb_fcliente = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        cb_cliente_entrada = new javax.swing.JComboBox<>();
        cb_cliente_sopa = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cb_cliente_fuerte = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cb_cliente_postre = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cb_cliente_chef = new javax.swing.JComboBox<>();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_nuevochef = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        tf_nombrechef = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sp_edadchef = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        rb_mchef = new javax.swing.JRadioButton();
        rb_fchef = new javax.swing.JRadioButton();
        jButton11 = new javax.swing.JButton();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_cliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_chef = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel4.setText("Nombre");

        jLabel5.setText("Edad");

        jLabel6.setText("Sexo");

        buttonGroup1.add(rb_mcliente);
        rb_mcliente.setText("M");

        buttonGroup1.add(rb_fcliente);
        rb_fcliente.setText("F");

        jLabel7.setText("Entrada");

        jLabel8.setText("Sopa");

        jLabel9.setText("Plato Fuerte");

        jLabel10.setText("Postre");

        jButton10.setText("Guardar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel11.setText("Chef a solicitar");

        javax.swing.GroupLayout jd_nuevoclienteLayout = new javax.swing.GroupLayout(jd_nuevocliente.getContentPane());
        jd_nuevocliente.getContentPane().setLayout(jd_nuevoclienteLayout);
        jd_nuevoclienteLayout.setHorizontalGroup(
            jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(cb_cliente_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb_cliente_fuerte, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(cb_cliente_postre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                        .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tf_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                                .addComponent(rb_mcliente)
                                                .addGap(4, 4, 4)
                                                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(sp_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(rb_fcliente))))
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(cb_cliente_chef, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(cb_cliente_sopa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jd_nuevoclienteLayout.setVerticalGroup(
            jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevoclienteLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(cb_cliente_chef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(tf_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sp_edadcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rb_mcliente)
                    .addComponent(rb_fcliente))
                .addGap(52, 52, 52)
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cb_cliente_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cb_cliente_fuerte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_nuevoclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cb_cliente_sopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cb_cliente_postre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel13.setText("Nombre");

        jLabel14.setText("Edad");

        jLabel15.setText("Sexo");

        buttonGroup2.add(rb_mchef);
        rb_mchef.setSelected(true);
        rb_mchef.setText("M");

        buttonGroup2.add(rb_fchef);
        rb_fchef.setText("F");

        jButton11.setText("Guardar");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_nuevochefLayout = new javax.swing.GroupLayout(jd_nuevochef.getContentPane());
        jd_nuevochef.getContentPane().setLayout(jd_nuevochefLayout);
        jd_nuevochefLayout.setHorizontalGroup(
            jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevochefLayout.createSequentialGroup()
                .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_nuevochefLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_nombrechef, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rb_mchef))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jd_nuevochefLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(rb_fchef))
                                .addComponent(sp_edadchef, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jd_nuevochefLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jd_nuevochefLayout.setVerticalGroup(
            jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_nuevochefLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_nombrechef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(sp_edadchef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jd_nuevochefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb_mchef)
                    .addComponent(rb_fchef)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(780, 580));
        setSize(new java.awt.Dimension(780, 580));
        getContentPane().setLayout(null);

        jt_cliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Entrada", "Sopa", "Plato Fuerte", "Postre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_cliente);
        if (jt_cliente.getColumnModel().getColumnCount() > 0) {
            jt_cliente.getColumnModel().getColumn(0).setHeaderValue("Cliente");
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(230, 120, 519, 121);

        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(231, 104, 69, 14);

        jt_chef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Platillo", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt_chef);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(230, 300, 519, 121);

        jLabel2.setText("Chefs");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 280, 69, 14);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(230, 470, 519, 36);

        jButton1.setText("Preparar");
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 440, 103, 23);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bienvenidos a Mamarr'e");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(202, 20, 324, 33);

        jButton2.setBackground(new java.awt.Color(0, 0, 102));
        jButton2.setText("Agregar Cliente");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 160, 111, 23);

        jButton3.setBackground(new java.awt.Color(0, 0, 102));
        jButton3.setText("Eliminar Cliente");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 200, 110, 23);

        jButton4.setBackground(new java.awt.Color(102, 102, 0));
        jButton4.setText("Agregar Platillo");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(30, 270, 111, 23);

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setText("Despedir Chef");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(30, 380, 110, 23);

        jButton8.setBackground(new java.awt.Color(153, 0, 0));
        jButton8.setText("Contratar Chef");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(30, 340, 110, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel12.setText("(Presionar para cargar platillos)");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 250, 120, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        try {
            String nombre;
            int edad;
            String sexo="";
            Platillo entrada;
            Platillo sopa;
            Platillo fuerte;
            Platillo postre;

            nombre = tf_nombrecliente.getText();
            edad = (Integer) sp_edadcliente.getValue();
            if (rb_mcliente.isSelected()){
                sexo="M";
            }
            else{
                sexo ="F";
            }
            entrada = (Platillo) cb_cliente_entrada.getSelectedItem();
            sopa = (Platillo) cb_cliente_sopa.getSelectedItem();
            fuerte = (Platillo) cb_cliente_fuerte.getSelectedItem();
            postre = (Platillo) cb_cliente_postre.getSelectedItem();
            
            clientes.add(new Cliente(nombre, edad, sexo, new Orden (entrada, sopa, fuerte, postre)));
            
            DefaultTableModel temp = (DefaultTableModel) jt_cliente.getModel();
            Object[] temp2 = new Object[4];
            temp2[0] = nombre;
            temp2[1] = entrada.getNombre();
            temp2[2] = sopa.getNombre();
            temp2[3] = fuerte.getNombre();
            temp2[4] = postre.getNombre();
            temp.addRow(temp2);
            jt_cliente.setModel(temp);
            
            jd_nuevocliente.setVisible(false);
            jd_nuevocliente.setModal(false);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultComboBoxModel cb1 = (DefaultComboBoxModel) cb_cliente_entrada.getModel();
        DefaultComboBoxModel cb2 = (DefaultComboBoxModel) cb_cliente_sopa.getModel();
        DefaultComboBoxModel cb3 = (DefaultComboBoxModel) cb_cliente_fuerte.getModel();
        DefaultComboBoxModel cb4 = (DefaultComboBoxModel) cb_cliente_postre.getModel();
        ap.cargarArchivo();
        for (Platillo t : platillos) {
            if (t.getTipo().equals("entrada")){
                cb1.addElement(t);
            }
            if (t.getTipo().equals("sopa")){
                cb2.addElement(t);
            }
            if (t.getTipo().equals("fuerte")){
                cb3.addElement(t);
            }
            if (t.getTipo().equals("postre")){
                cb4.addElement(t);
            }
            cb_cliente_entrada.setModel(cb1);
            cb_cliente_sopa.setModel(cb2);
            cb_cliente_fuerte.setModel(cb3);
            cb_cliente_postre.setModel(cb4);
        }
        
        DefaultComboBoxModel cb5 = (DefaultComboBoxModel) cb_cliente_chef.getModel();
        for (Chef t : chefs) {
            cb5.addElement(t);
        }
        cb_cliente_chef.setModel(cb5);
        
        jd_nuevocliente.setModal(true);
        jd_nuevocliente.pack();
        jd_nuevocliente.setLocationRelativeTo(this);
        jd_nuevocliente.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        platillos.add(new Platillo("Tortilla", 9, 0, new Date(), Color.red, "sopa"));
        platillos.add(new Platillo("Res", 12, 0, new Date(), Color.black, "sopa"));
        platillos.add(new Platillo("Pollo", 10, 0, new Date(), Color.yellow, "sopa"));
        platillos.add(new Platillo("Capirotada", 7, 0, new Date(), Color.white, "sopa"));
        platillos.add(new Platillo("Pollo con pure", 15, 0, new Date(), Color.black, "fuerte"));
        platillos.add(new Platillo("Espaguetis", 13, 0, new Date(), Color.red, "fuerte"));
        platillos.add(new Platillo("Hamburguesa", 11, 0, new Date(), Color.yellow, "fuerte"));
        platillos.add(new Platillo("Salmon", 18, 0, new Date(), Color.pink, "fuerte"));
        platillos.add(new Platillo("Cordero", 16, 0, new Date(), Color.white, "fuerte"));
        platillos.add(new Platillo("Pie de Limon", 7, 0, new Date(), Color.green, "postre"));
        platillos.add(new Platillo("Cheesecake", 8, 0, new Date(), Color.red, "postre"));
        platillos.add(new Platillo("Tarimasu", 9, 0, new Date(), Color.black, "postre"));
        platillos.add(new Platillo("Crepa", 6, 0, new Date(), Color.yellow, "postre"));
        platillos.add(new Platillo("Anafre Parisiense", 5, 0, new Date(), Color.black, "entrada"));
        platillos.add(new Platillo("Empanada", 7, 0, new Date(), Color.red, "entrada"));
        platillos.add(new Platillo("Huevos Rellenos", 3, 0, new Date(), Color.white, "entrada"));
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        jt_cliente.remove(jt_cliente.getSelectedRow());
        clientes.remove(jt_cliente.getSelectedRow());
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        jd_nuevochef.setModal(true);
        jd_nuevochef.pack();
        jd_nuevochef.setLocationRelativeTo(this);
        jd_nuevochef.setVisible(true);
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        try {
            String nombre;
            int edad;
            String sexo="";
            nombre = tf_nombrechef.getText();
            edad = (Integer) sp_edadchef.getValue();
            if (rb_mchef.isSelected()){
                sexo="M";
            }
            else{
                sexo ="F";
            }
            chefs.add(new Chef(nombre, edad, sexo));
        } catch (Exception e) {
        }
        jd_nuevochef.setVisible(false);
        jd_nuevochef.setModal(false);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jt_chef.remove(jt_cliente.getSelectedRow());
        chefs.remove(jt_cliente.getSelectedRow());
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plataforma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new plataforma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_cliente_chef;
    private javax.swing.JComboBox<String> cb_cliente_entrada;
    private javax.swing.JComboBox<String> cb_cliente_fuerte;
    private javax.swing.JComboBox<String> cb_cliente_postre;
    private javax.swing.JComboBox<String> cb_cliente_sopa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_nuevochef;
    private javax.swing.JDialog jd_nuevocliente;
    private javax.swing.JTable jt_chef;
    private javax.swing.JTable jt_cliente;
    private javax.swing.JRadioButton rb_fchef;
    private javax.swing.JRadioButton rb_fcliente;
    private javax.swing.JRadioButton rb_mchef;
    private javax.swing.JRadioButton rb_mcliente;
    private javax.swing.JSpinner sp_edadchef;
    private javax.swing.JSpinner sp_edadcliente;
    private javax.swing.JTextField tf_nombrechef;
    private javax.swing.JTextField tf_nombrecliente;
    // End of variables declaration//GEN-END:variables
ArrayList <Platillo> platillos = new ArrayList();
ArrayList <Cliente> clientes = new ArrayList();
ArrayList <Chef> chefs = new ArrayList();
}
